name: seazit
channels:
  - anaconda-platform
  - conda-forge
  - defaults
dependencies:
  - yarn=4.3.1
  - nodejs=22.5.1
  - python=3.8
  - certifi=2024.07.04

  #- python=3.6.1  # required per https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg07315.html

