version: '2'
 
volumes:
  postgres_data: {}
  postgres_backup: {}
  shiny_apps: {}
  static_files: {}

services:
  #postgres:
    #restart: always
    #build: ./compose/postgres
    #command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    #volumes:
      #- postgres_data:/var/lib/postgresql/data
      #- postgres_backup:/backups
    #env_file: .env
    #ports:
      #- "0.0.0.0:5437:5432"

  rabbitmq:
    restart: always
    build: ./compose/rabbitmq
    ports:
      - "0.0.0.0:5671:5671"

  redis:
    restart: always
    build: ./compose/redis
    ports:
      - "0.0.0.0:6380:6379"

  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-staging
    command: /usr/bin/supervisord -c /supervisord.conf --nodaemon
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - rserve
    env_file: .env
    volumes:
      - static_files:/app/public
      #- postgres_backup:/backups

  shiny:
    restart: always
    build:
      context: ./compose/shiny
      dockerfile: Dockerfile-dev
    ports:
      - "0.0.0.0:3839:3838"
    volumes:
      - shiny_apps:/srv/shiny-apps
 
  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - django
      - shiny
    ports:
      - "0.0.0.0:81:80"
      - "0.0.0.0:444:443"
    volumes:
      - static_files:/app/public

  rserve:
    restart: always
    build: ./compose/rserve
    ports:
      - "0.0.0.0:6312:6311"
