version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  shiny_apps: {}
  static_files: {}

services:

  #postgres:
    #restart: always
    #build: ./compose/postgres
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    #  - postgres_backup:/backups
    #env_file: .env

  rabbitmq:
    restart: always
    build: ./compose/rabbitmq 
    ports:
      - "0.0.0.0:5672:5672"    

  redis:
    restart: always
    build: ./compose/redis
    ports:
      - "0.0.0.0:6379:6379"  
     

  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /usr/bin/supervisord -c /supervisord.conf --nodaemon
    #sue Jan 30
    #ports:
      #- "0.0.0.0:5000:5000"
    depends_on:
      #- postgres
      - rabbitmq
      - redis
      #- rserve
    env_file: .env
    volumes:
      - static_files:/app/public
      #- postgres_backup:/backups

  rserve:
    restart: always
    build: ./compose/rserve
    ports:
      - "0.0.0.0:6311:6311"

  shiny:
    restart: always
    build: ./compose/shiny
    ports:
      - "0.0.0.0:3838:3838"
    volumes:
      - shiny_apps:/srv/shiny-apps

  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - django
      #- shiny
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - static_files:/app/public
