# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import neurotox.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
         
    ]
