# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import neurotox.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assay",
            fields=[
                (
                    "protocol",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("provider", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "name",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                )
            ],
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "casrn",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("ntp80", models.BooleanField(default=False)),
                ("ntp91", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="neurotox.Category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurveP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_increasing", models.BooleanField()),
                ("is_active", models.BooleanField(default=False)),
                ("bmd", models.FloatField(null=True)),
                ("bmr", models.FloatField(null=True, verbose_name="BMR")),
                ("wauc", models.FloatField(null=True)),
                ("emax", models.FloatField(null=True)),
                (
                    "doses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                (
                    "responses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=None
                    ),
                ),
                ("comments", models.CharField(max_length=128)),
                ("selectivity_ratio", models.FloatField(null=True)),
                ("is_selective", models.BooleanField(default=False)),
                ("has_viability_bmd", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "CurveP BMD",
                "verbose_name_plural": "CurveP BMDs",
            },
            bases=(neurotox.models.BmdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Hill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_increasing", models.BooleanField()),
                ("is_active", models.BooleanField(default=False)),
                ("bmd", models.FloatField(null=True, verbose_name="BMD")),
                ("bmr", models.FloatField(null=True, verbose_name="BMR")),
                ("bmdl", models.FloatField(null=True, verbose_name="BMDL")),
                ("bmdu", models.FloatField(null=True, verbose_name="BMDU")),
                ("param_vmax", models.FloatField(null=True, verbose_name="Vmax")),
                ("param_k", models.FloatField(null=True, verbose_name="K")),
                ("param_n", models.FloatField(null=True, verbose_name="N")),
                ("selectivity_ratio", models.FloatField(null=True)),
                ("is_selective", models.BooleanField(default=False)),
                ("has_viability_bmd", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Hill curve BMD",
                "verbose_name_plural": "Hill curve BMDs",
            },
            bases=(neurotox.models.BmdMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("size", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to="neurotox.Assay",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Readout",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=32)),
                ("is_viability", models.BooleanField(default=False)),
                ("calculate_bmc", models.BooleanField(default=False)),
                (
                    "directionality",
                    models.SmallIntegerField(
                        choices=[
                            (-1, "Negative only"),
                            (0, "Negative and positive"),
                            (1, "Positive only"),
                            (999, "No direction"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readouts",
                        to="neurotox.Assay",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Substance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lot", models.CharField(blank=True, max_length=16)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurotox.Chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Well",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.PositiveSmallIntegerField(null=True)),
                ("column_index", models.PositiveSmallIntegerField(null=True)),
                ("vehicle_control", models.BooleanField(default=False)),
                ("positive_control", models.BooleanField(default=False)),
                ("concentration", models.FloatField()),
                ("chemical_ship_position", models.CharField(blank=True, max_length=4)),
                (
                    "plate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wells",
                        to="neurotox.Plate",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wells",
                        to="neurotox.Substance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WellResponse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_raw", models.FloatField(null=True)),
                ("response_normalized", models.FloatField(null=True)),
                ("is_outlier", models.BooleanField(default=False)),
                (
                    "readout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neurotox.Readout",
                    ),
                ),
                (
                    "well",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="neurotox.Well"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hill",
            name="readout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="neurotox.Readout"
            ),
        ),
        migrations.AddField(
            model_name="hill",
            name="substance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="neurotox.Substance"
            ),
        ),
        migrations.AddField(
            model_name="curvep",
            name="readout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="neurotox.Readout"
            ),
        ),
        migrations.AddField(
            model_name="curvep",
            name="substance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="neurotox.Substance"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wellresponse", unique_together=set([("well", "readout")])
        ),
        migrations.AlterUniqueTogether(
            name="substance", unique_together=set([("lot", "chemical")])
        ),
        migrations.AlterUniqueTogether(
            name="readout", unique_together=set([("protocol", "endpoint")])
        ),
        migrations.AlterUniqueTogether(
            name="plate", unique_together=set([("protocol", "name")])
        ),
    ]
