# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("neurotox", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="curvep",
            name="bmdl",
            field=models.FloatField(null=True, verbose_name="BMDL"),
        ),
        migrations.AddField(
            model_name="curvep",
            name="bmdu",
            field=models.FloatField(null=True, verbose_name="BMDU"),
        ),
    ]
