# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("neurotox", "0001_initial")]

    operations = [
         
    ]
