# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-17 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurotox', '0002_add_bmdl_bmdu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curvep',
            name='is_selective',
        ),
        migrations.RemoveField(
            model_name='hill',
            name='is_selective',
        ),
    ]
