# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-10-07 21:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import neurotox.models


class Migration(migrations.Migration):

    dependencies = [
        ('neurotox', '0003_remove_is_selective'),
    ]

    operations = [
        migrations.CreateModel(
            name='expo_curvep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_increasing', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('bmd', models.FloatField(null=True)),
                ('bmdl', models.FloatField(null=True, verbose_name='BMDL')),
                ('bmdu', models.FloatField(null=True, verbose_name='BMDU')),
                ('bmr', models.FloatField(null=True, verbose_name='BMR')),
                ('wauc', models.FloatField(null=True)),
                ('emax', models.FloatField(null=True)),
                ('doses', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('responses', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('comments', models.CharField(max_length=128)),
                ('selectivity_ratio', models.FloatField(null=True)),
                ('has_viability_bmd', models.BooleanField(default=False)),
                ('seem3_cmean', models.FloatField(null=True)),
                ('seem3_l95', models.FloatField(null=True)),
                ('seem3_u95', models.FloatField(null=True)),
                ('readout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurotox.Readout')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurotox.Substance')),
            ],
            options={
                'verbose_name': 'CurveP BMD',
                'verbose_name_plural': 'CurveP BMDs',
            },
            bases=(neurotox.models.ExposureBmdMixin, models.Model),
        ),
        migrations.CreateModel(
            name='expo_hill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_increasing', models.BooleanField()),
                ('is_active', models.BooleanField(default=False)),
                ('bmd', models.FloatField(null=True, verbose_name='BMD')),
                ('bmr', models.FloatField(null=True, verbose_name='BMR')),
                ('bmdl', models.FloatField(null=True, verbose_name='BMDL')),
                ('bmdu', models.FloatField(null=True, verbose_name='BMDU')),
                ('param_vmax', models.FloatField(null=True, verbose_name='Vmax')),
                ('param_k', models.FloatField(null=True, verbose_name='K')),
                ('param_n', models.FloatField(null=True, verbose_name='N')),
                ('selectivity_ratio', models.FloatField(null=True)),
                ('has_viability_bmd', models.BooleanField(default=False)),
                ('seem3_cmean', models.FloatField(null=True)),
                ('seem3_l95', models.FloatField(null=True)),
                ('seem3_u95', models.FloatField(null=True)),
                ('readout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurotox.Readout')),
                ('substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurotox.Substance')),
            ],
            options={
                'verbose_name': 'Hill curve BMD',
                'verbose_name_plural': 'Hill curve BMDs',
            },
            bases=(neurotox.models.ExposureBmdMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('casrn', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('seem3_cmean', models.FloatField(null=True)),
                ('seem3_l95', models.FloatField(null=True)),
                ('seem3_u95', models.FloatField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exposure',
            unique_together=set([('casrn', 'seem3_cmean')]),
        ),
    ]
