# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-10-07 21:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import neurotox.models


class Migration(migrations.Migration):

    dependencies = [
        ('neurotox', '0003_remove_is_selective'),
    ]

    operations = [
         
    ]
