site_name: NTP Sandbox
theme: readthedocs
#pages:
nav:
- NTP Sandbox: index.md
- Installation: installation.md
- Applications:
  - Overview: apps/index.md
  - CEBS summary data browser: apps/cebs.md  
  - Neurotoxicity workshop: apps/neurotox.md
#  - Fiveday: apps/fiveday.md
  #- RoC PDFs: apps/roc_pdfs.md
  - Shiny applications: apps/shiny.md
- Database:
  - Overview: db/index.md
  - Schema details: db/schema.md
- Contributing: contributing.md
- Deploying: deploying.md
markdown_extensions:
  - toc:
      permalink: true
